// Mocks generated by Mockito 5.4.4 from annotations
// in flauncher/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:io' as _i16;
import 'dart:typed_data' as _i14;
import 'dart:ui' as _i4;

import 'package:drift/drift.dart' as _i7;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i9;
import 'package:flauncher/database.dart' as _i8;
import 'package:flauncher/flauncher_channel.dart' as _i13;
import 'package:flauncher/gradients.dart' as _i2;
import 'package:flauncher/models/app.dart' as _i18;
import 'package:flauncher/models/category.dart' as _i3;
import 'package:flauncher/models/scene.dart' as _i5;
import 'package:flauncher/providers/apps_service.dart' as _i17;
import 'package:flauncher/providers/scenes_service.dart' as _i21;
import 'package:flauncher/providers/settings_service.dart' as _i19;
import 'package:flauncher/providers/wallpaper_service.dart' as _i15;
import 'package:flutter/cupertino.dart' as _i11;
import 'package:flutter/services.dart' as _i12;
import 'package:image_picker/image_picker.dart' as _i22;
import 'package:image_picker_platform_interface/image_picker_platform_interface.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i20;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFLauncherGradient_0 extends _i1.SmartFake
    implements _i2.FLauncherGradient {
  _FakeFLauncherGradient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategory_1 extends _i1.SmartFake implements _i3.Category {
  _FakeCategory_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColor_2 extends _i1.SmartFake implements _i4.Color {
  _FakeColor_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScene_3 extends _i1.SmartFake implements _i5.Scene {
  _FakeScene_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLostDataResponse_4 extends _i1.SmartFake
    implements _i6.LostDataResponse {
  _FakeLostDataResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrationStrategy_5 extends _i1.SmartFake
    implements _i7.MigrationStrategy {
  _FakeMigrationStrategy_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppsTable_6 extends _i1.SmartFake implements _i8.$AppsTable {
  _Fake$AppsTable_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$CategoriesTable_7 extends _i1.SmartFake
    implements _i8.$CategoriesTable {
  _Fake$CategoriesTable_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppsCategoriesTable_8 extends _i1.SmartFake
    implements _i8.$AppsCategoriesTable {
  _Fake$AppsCategoriesTable_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$LauncherSpacersTable_9 extends _i1.SmartFake
    implements _i8.$LauncherSpacersTable {
  _Fake$LauncherSpacersTable_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$FLauncherDatabaseManager_10 extends _i1.SmartFake
    implements _i8.$FLauncherDatabaseManager {
  _Fake$FLauncherDatabaseManager_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_11 extends _i1.SmartFake
    implements _i7.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_12 extends _i1.SmartFake
    implements _i7.GeneratedDatabase {
  _FakeGeneratedDatabase_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_13 extends _i1.SmartFake
    implements _i7.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_14 extends _i1.SmartFake
    implements _i7.DatabaseConnection {
  _FakeDatabaseConnection_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_15 extends _i1.SmartFake implements _i7.QueryExecutor {
  _FakeQueryExecutor_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_16 extends _i1.SmartFake
    implements _i9.StreamQueryStore {
  _FakeStreamQueryStore_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_17 extends _i1.SmartFake
    implements _i7.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_18 extends _i1.SmartFake implements _i7.Migrator {
  _FakeMigrator_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_19<T1> extends _i1.SmartFake implements _i10.Future<T1> {
  _FakeFuture_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_20<T1 extends _i7.Table, D1> extends _i1.SmartFake
    implements _i7.InsertStatement<T1, D1> {
  _FakeInsertStatement_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_21<T extends _i7.Table, D> extends _i1.SmartFake
    implements _i7.UpdateStatement<T, D> {
  _FakeUpdateStatement_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_22<T1 extends _i7.HasResultSet, D>
    extends _i1.SmartFake implements _i7.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_23<FirstT extends _i7.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i7.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_24<T> extends _i1.SmartFake implements _i7.Selectable<T> {
  _FakeSelectable_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_25<T1 extends _i7.Table, D1> extends _i1.SmartFake
    implements _i7.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_26 extends _i1.SmartFake
    implements _i7.GenerationContext {
  _FakeGenerationContext_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageStream_27 extends _i1.SmartFake implements _i11.ImageStream {
  _FakeImageStream_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString(
          {_i12.DiagnosticLevel? minLevel = _i12.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeImageStreamCompleter_28 extends _i1.SmartFake
    implements _i11.ImageStreamCompleter {
  _FakeImageStreamCompleter_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString(
          {_i12.DiagnosticLevel? minLevel = _i12.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [FLauncherChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockFLauncherChannel extends _i1.Mock implements _i13.FLauncherChannel {
  MockFLauncherChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<Map<dynamic, dynamic>>> getApplications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getApplications,
          [],
        ),
        returnValue: _i10.Future<List<Map<dynamic, dynamic>>>.value(
            <Map<dynamic, dynamic>>[]),
      ) as _i10.Future<List<Map<dynamic, dynamic>>>);

  @override
  _i10.Future<_i14.Uint8List> getApplicationBanner(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApplicationBanner,
          [packageName],
        ),
        returnValue: _i10.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
      ) as _i10.Future<_i14.Uint8List>);

  @override
  _i10.Future<_i14.Uint8List> getApplicationIcon(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApplicationIcon,
          [packageName],
        ),
        returnValue: _i10.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
      ) as _i10.Future<_i14.Uint8List>);

  @override
  _i10.Future<bool> applicationExists(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #applicationExists,
          [packageName],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> launchActivityFromAction(String? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #launchActivityFromAction,
          [action],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> launchApp(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #launchApp,
          [packageName],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> openSettings() => (super.noSuchMethod(
        Invocation.method(
          #openSettings,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> openAppInfo(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #openAppInfo,
          [packageName],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> uninstallApp(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #uninstallApp,
          [packageName],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> isDefaultLauncher() => (super.noSuchMethod(
        Invocation.method(
          #isDefaultLauncher,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<bool> checkForGetContentAvailability() => (super.noSuchMethod(
        Invocation.method(
          #checkForGetContentAvailability,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<Map<String, dynamic>> getActiveNetworkInformation() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNetworkInformation,
          [],
        ),
        returnValue:
            _i10.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<int> getDailyWifiUsage() => (super.noSuchMethod(
        Invocation.method(
          #getDailyWifiUsage,
          [],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<int> getWeeklyWifiUsage() => (super.noSuchMethod(
        Invocation.method(
          #getWeeklyWifiUsage,
          [],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<int> getMonthlyWifiUsage() => (super.noSuchMethod(
        Invocation.method(
          #getMonthlyWifiUsage,
          [],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<bool> checkUsageStatsPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkUsageStatsPermission,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> requestUsageStatsPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestUsageStatsPermission,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> openWifiSettings() => (super.noSuchMethod(
        Invocation.method(
          #openWifiSettings,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> startAmbientMode() => (super.noSuchMethod(
        Invocation.method(
          #startAmbientMode,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> checkMediaPermissions() => (super.noSuchMethod(
        Invocation.method(
          #checkMediaPermissions,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> requestMediaPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestMediaPermissions,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getMediaStoreImages() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaStoreImages,
          [],
        ),
        returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getMediaStoreVideos() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaStoreVideos,
          [],
        ),
        returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<_i14.Uint8List?> getMediaStoreVideoThumbnail(
    int? id, {
    String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaStoreVideoThumbnail,
          [id],
          {#path: path},
        ),
        returnValue: _i10.Future<_i14.Uint8List?>.value(),
      ) as _i10.Future<_i14.Uint8List?>);

  @override
  _i10.Future<bool> installApk(String? apkPath) => (super.noSuchMethod(
        Invocation.method(
          #installApk,
          [apkPath],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> requestInstallUnknownAppsPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestInstallUnknownAppsPermission,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void addAppsChangedListener(void Function(Map<String, dynamic>)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addAppsChangedListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addNetworkChangedListener(
          void Function(Map<String, dynamic>)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addNetworkChangedListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<bool> checkWatchNextPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkWatchNextPermission,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> requestWatchNextPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestWatchNextPermission,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<Map<dynamic, dynamic>>> getWatchNextItems() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchNextItems,
          [],
        ),
        returnValue: _i10.Future<List<Map<dynamic, dynamic>>>.value(
            <Map<dynamic, dynamic>>[]),
      ) as _i10.Future<List<Map<dynamic, dynamic>>>);

  @override
  _i10.Future<bool> launchWatchNextItem(
    String? packageName,
    String? contentId,
    String? action,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #launchWatchNextItem,
          [
            packageName,
            contentId,
            action,
          ],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i14.Uint8List> loadContentUriImage(String? contentUri) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadContentUriImage,
          [contentUri],
        ),
        returnValue: _i10.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
      ) as _i10.Future<_i14.Uint8List>);
}

/// A class which mocks [WallpaperService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWallpaperService extends _i1.Mock implements _i15.WallpaperService {
  MockWallpaperService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get wallpaperRevision => (super.noSuchMethod(
        Invocation.getter(#wallpaperRevision),
        returnValue: 0,
      ) as int);

  @override
  _i2.FLauncherGradient get gradient => (super.noSuchMethod(
        Invocation.getter(#gradient),
        returnValue: _FakeFLauncherGradient_0(
          this,
          Invocation.getter(#gradient),
        ),
      ) as _i2.FLauncherGradient);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void debugResolveNow() => super.noSuchMethod(
        Invocation.method(
          #debugResolveNow,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> pickWallpaper(_i16.File? sourceFile) => (super.noSuchMethod(
        Invocation.method(
          #pickWallpaper,
          [sourceFile],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> pickWallpaperDay(_i16.File? sourceFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickWallpaperDay,
          [sourceFile],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> pickWallpaperNight(_i16.File? sourceFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickWallpaperNight,
          [sourceFile],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> pickVideoWallpaper(_i16.File? sourceFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickVideoWallpaper,
          [sourceFile],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> pickVideoWallpaperDay(_i16.File? sourceFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickVideoWallpaperDay,
          [sourceFile],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> pickVideoWallpaperNight(_i16.File? sourceFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickVideoWallpaperNight,
          [sourceFile],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setGradient(_i2.FLauncherGradient? fLauncherGradient) =>
      (super.noSuchMethod(
        Invocation.method(
          #setGradient,
          [fLauncherGradient],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cleanVideoWallpaperFiles() => (super.noSuchMethod(
        Invocation.method(
          #cleanVideoWallpaperFiles,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cleanImageWallpaperFiles() => (super.noSuchMethod(
        Invocation.method(
          #cleanImageWallpaperFiles,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppsService extends _i1.Mock implements _i17.AppsService {
  MockAppsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  int get layoutVersion => (super.noSuchMethod(
        Invocation.getter(#layoutVersion),
        returnValue: 0,
      ) as int);

  @override
  List<_i18.App> get applications => (super.noSuchMethod(
        Invocation.getter(#applications),
        returnValue: <_i18.App>[],
      ) as List<_i18.App>);

  @override
  List<_i3.LauncherSection> get launcherSections => (super.noSuchMethod(
        Invocation.getter(#launcherSections),
        returnValue: <_i3.LauncherSection>[],
      ) as List<_i3.LauncherSection>);

  @override
  List<_i3.Category> get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: <_i3.Category>[],
      ) as List<_i3.Category>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearPendingReorderFocusPackage() => super.noSuchMethod(
        Invocation.method(
          #clearPendingReorderFocusPackage,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPendingReorderFocus(
    String? packageName,
    int? categoryId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setPendingReorderFocus,
          [
            packageName,
            categoryId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool consumeDirtyImage(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #consumeDirtyImage,
          [packageName],
        ),
        returnValue: false,
      ) as bool);

  @override
  void sortCategory(_i3.Category? category) => super.noSuchMethod(
        Invocation.method(
          #sortCategory,
          [category],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i14.Uint8List> getAppBanner(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppBanner,
          [packageName],
        ),
        returnValue: _i10.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
      ) as _i10.Future<_i14.Uint8List>);

  @override
  _i10.Future<void> setCustomAppBanner(
    String? packageName,
    String? imagePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCustomAppBanner,
          [
            packageName,
            imagePath,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> removeCustomAppBanner(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCustomAppBanner,
          [packageName],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> hasCustomBanner(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #hasCustomBanner,
          [packageName],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<_i14.Uint8List> getAppIcon(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppIcon,
          [packageName],
        ),
        returnValue: _i10.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
      ) as _i10.Future<_i14.Uint8List>);

  @override
  _i10.Future<void> launchApp(_i18.App? app) => (super.noSuchMethod(
        Invocation.method(
          #launchApp,
          [app],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> openAppInfo(_i18.App? app) => (super.noSuchMethod(
        Invocation.method(
          #openAppInfo,
          [app],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> uninstallApp(_i18.App? app) => (super.noSuchMethod(
        Invocation.method(
          #uninstallApp,
          [app],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> openSettings() => (super.noSuchMethod(
        Invocation.method(
          #openSettings,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<bool> isDefaultLauncher() => (super.noSuchMethod(
        Invocation.method(
          #isDefaultLauncher,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<void> startAmbientMode() => (super.noSuchMethod(
        Invocation.method(
          #startAmbientMode,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> addToCategory(
    _i18.App? app,
    _i3.Category? category, {
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToCategory,
          [
            app,
            category,
          ],
          {#shouldNotifyListeners: shouldNotifyListeners},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> removeFromCategory(
    _i18.App? application,
    _i3.Category? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromCategory,
          [
            application,
            category,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> autoPopulateCategory(_i3.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #autoPopulateCategory,
          [category],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i3.Category> getOrCreateFavoritesCategory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateFavoritesCategory,
          [],
        ),
        returnValue: _i10.Future<_i3.Category>.value(_FakeCategory_1(
          this,
          Invocation.method(
            #getOrCreateFavoritesCategory,
            [],
          ),
        )),
      ) as _i10.Future<_i3.Category>);

  @override
  bool isAppInFavorites(_i18.App? app) => (super.noSuchMethod(
        Invocation.method(
          #isAppInFavorites,
          [app],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> addToFavorites(_i18.App? app) => (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [app],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> removeFromFavorites(_i18.App? app) => (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [app],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> toggleFavorite(_i18.App? app) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [app],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveApplicationOrderInCategory(_i3.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveApplicationOrderInCategory,
          [category],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> moveAppToAdjacentCategory(
    _i18.App? app,
    _i3.Category? currentCategory,
    _i11.AxisDirection? direction,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveAppToAdjacentCategory,
          [
            app,
            currentCategory,
            direction,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void reorderApplication(
    _i3.Category? category,
    int? oldIndex,
    int? newIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #reorderApplication,
          [
            category,
            oldIndex,
            newIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<int> addCategory(
    String? categoryName, {
    _i3.CategorySort? sort = _i3.CategorySort.manual,
    _i3.CategoryType? type = _i3.CategoryType.grid,
    int? columnsCount = 6,
    int? rowHeight = 110,
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [categoryName],
          {
            #sort: sort,
            #type: type,
            #columnsCount: columnsCount,
            #rowHeight: rowHeight,
            #shouldNotifyListeners: shouldNotifyListeners,
          },
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> updateCategory(
    int? categoryId,
    String? name,
    _i3.CategorySort? sort,
    _i3.CategoryType? type,
    int? columnsCount,
    int? rowHeight, {
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [
            categoryId,
            name,
            sort,
            type,
            columnsCount,
            rowHeight,
          ],
          {#shouldNotifyListeners: shouldNotifyListeners},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> addSpacer(int? height) => (super.noSuchMethod(
        Invocation.method(
          #addSpacer,
          [height],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateSpacerHeight(
    _i3.LauncherSpacer? spacer,
    int? height,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSpacerHeight,
          [
            spacer,
            height,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> renameCategory(
    _i3.Category? category,
    String? categoryName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameCategory,
          [
            category,
            categoryName,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteSection(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteSection,
          [index],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void moveSectionInMemory(
    int? oldIndex,
    int? newIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #moveSectionInMemory,
          [
            oldIndex,
            newIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> persistSectionsOrder() => (super.noSuchMethod(
        Invocation.method(
          #persistSectionsOrder,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> moveSection(
    int? oldIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveSection,
          [
            oldIndex,
            newIndex,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> hideApplication(_i18.App? application) =>
      (super.noSuchMethod(
        Invocation.method(
          #hideApplication,
          [application],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> showApplication(_i18.App? application) =>
      (super.noSuchMethod(
        Invocation.method(
          #showApplication,
          [application],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setCategoryType(
    _i3.Category? category,
    _i3.CategoryType? type, {
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCategoryType,
          [
            category,
            type,
          ],
          {#shouldNotifyListeners: shouldNotifyListeners},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setCategorySort(
    _i3.Category? category,
    _i3.CategorySort? sort,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCategorySort,
          [
            category,
            sort,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setCategoryColumnsCount(
    _i3.Category? category,
    int? columnsCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCategoryColumnsCount,
          [
            category,
            columnsCount,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setCategoryRowHeight(
    _i3.Category? category,
    int? rowHeight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCategoryRowHeight,
          [
            category,
            rowHeight,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i19.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get appHighlightAnimationEnabled => (super.noSuchMethod(
        Invocation.getter(#appHighlightAnimationEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get appKeyClickEnabled => (super.noSuchMethod(
        Invocation.getter(#appKeyClickEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get autoHideAppBarEnabled => (super.noSuchMethod(
        Invocation.getter(#autoHideAppBarEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get showCategoryTitles => (super.noSuchMethod(
        Invocation.getter(#showCategoryTitles),
        returnValue: false,
      ) as bool);

  @override
  bool get showAppNamesBelowIcons => (super.noSuchMethod(
        Invocation.getter(#showAppNamesBelowIcons),
        returnValue: false,
      ) as bool);

  @override
  bool get showDateInStatusBar => (super.noSuchMethod(
        Invocation.getter(#showDateInStatusBar),
        returnValue: false,
      ) as bool);

  @override
  bool get showTimeInStatusBar => (super.noSuchMethod(
        Invocation.getter(#showTimeInStatusBar),
        returnValue: false,
      ) as bool);

  @override
  String get backButtonAction => (super.noSuchMethod(
        Invocation.getter(#backButtonAction),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.getter(#backButtonAction),
        ),
      ) as String);

  @override
  String get dateFormat => (super.noSuchMethod(
        Invocation.getter(#dateFormat),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.getter(#dateFormat),
        ),
      ) as String);

  @override
  String get timeFormat => (super.noSuchMethod(
        Invocation.getter(#timeFormat),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.getter(#timeFormat),
        ),
      ) as String);

  @override
  String get wifiUsagePeriod => (super.noSuchMethod(
        Invocation.getter(#wifiUsagePeriod),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.getter(#wifiUsagePeriod),
        ),
      ) as String);

  @override
  bool get showWifiWidgetInStatusBar => (super.noSuchMethod(
        Invocation.getter(#showWifiWidgetInStatusBar),
        returnValue: false,
      ) as bool);

  @override
  bool get showNetworkIndicatorInStatusBar => (super.noSuchMethod(
        Invocation.getter(#showNetworkIndicatorInStatusBar),
        returnValue: false,
      ) as bool);

  @override
  String get accentColorHex => (super.noSuchMethod(
        Invocation.getter(#accentColorHex),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.getter(#accentColorHex),
        ),
      ) as String);

  @override
  String get screensaverClockStyle => (super.noSuchMethod(
        Invocation.getter(#screensaverClockStyle),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.getter(#screensaverClockStyle),
        ),
      ) as String);

  @override
  bool get dockBackdropFilterDisabled => (super.noSuchMethod(
        Invocation.getter(#dockBackdropFilterDisabled),
        returnValue: false,
      ) as bool);

  @override
  bool get backgroundBlurDisabled => (super.noSuchMethod(
        Invocation.getter(#backgroundBlurDisabled),
        returnValue: false,
      ) as bool);

  @override
  bool get showWatchNextSection => (super.noSuchMethod(
        Invocation.getter(#showWatchNextSection),
        returnValue: false,
      ) as bool);

  @override
  bool get dockDarkBackground => (super.noSuchMethod(
        Invocation.getter(#dockDarkBackground),
        returnValue: false,
      ) as bool);

  @override
  bool get dockShadowEnabled => (super.noSuchMethod(
        Invocation.getter(#dockShadowEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get showFocusBorders => (super.noSuchMethod(
        Invocation.getter(#showFocusBorders),
        returnValue: false,
      ) as bool);

  @override
  _i4.Color get accentColor => (super.noSuchMethod(
        Invocation.getter(#accentColor),
        returnValue: _FakeColor_2(
          this,
          Invocation.getter(#accentColor),
        ),
      ) as _i4.Color);

  @override
  bool get timeBasedWallpaperEnabled => (super.noSuchMethod(
        Invocation.getter(#timeBasedWallpaperEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<void> set(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            key,
            value,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setAppHighlightAnimationEnabled(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAppHighlightAnimationEnabled,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setAppKeyClickEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAppKeyClickEnabled,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setAutoHideAppBarEnabled(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutoHideAppBarEnabled,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setGradientUuid(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setGradientUuid,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setBackButtonAction(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setBackButtonAction,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setDateTimeFormat(
    String? dateFormatString,
    String? timeFormatString,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDateTimeFormat,
          [
            dateFormatString,
            timeFormatString,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setShowCategoryTitles(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowCategoryTitles,
          [show],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setShowAppNamesBelowIcons(bool? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShowAppNamesBelowIcons,
          [show],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setShowDateInStatusBar(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowDateInStatusBar,
          [show],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setShowTimeInStatusBar(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowTimeInStatusBar,
          [show],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setWifiUsagePeriod(String? period) => (super.noSuchMethod(
        Invocation.method(
          #setWifiUsagePeriod,
          [period],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setShowWifiWidgetInStatusBar(bool? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShowWifiWidgetInStatusBar,
          [show],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setShowNetworkIndicatorInStatusBar(bool? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShowNetworkIndicatorInStatusBar,
          [show],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setAccentColor(String? colorHex) => (super.noSuchMethod(
        Invocation.method(
          #setAccentColor,
          [colorHex],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setScreensaverClockStyle(String? style) =>
      (super.noSuchMethod(
        Invocation.method(
          #setScreensaverClockStyle,
          [style],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setDockBackdropFilterDisabled(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDockBackdropFilterDisabled,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setBackgroundBlurDisabled(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBackgroundBlurDisabled,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setShowWatchNextSection(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setShowWatchNextSection,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setDockDarkBackground(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDockDarkBackground,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setDockShadowEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDockShadowEnabled,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setShowFocusBorders(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setShowFocusBorders,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setTimeBasedWallpaperEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTimeBasedWallpaperEnabled,
          [enabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ScenesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockScenesService extends _i1.Mock implements _i21.ScenesService {
  MockScenesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.Scene> get scenes => (super.noSuchMethod(
        Invocation.getter(#scenes),
        returnValue: <_i5.Scene>[],
      ) as List<_i5.Scene>);

  @override
  String get activeSceneKey => (super.noSuchMethod(
        Invocation.getter(#activeSceneKey),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.getter(#activeSceneKey),
        ),
      ) as String);

  @override
  _i5.Scene get activeScene => (super.noSuchMethod(
        Invocation.getter(#activeScene),
        returnValue: _FakeScene_3(
          this,
          Invocation.getter(#activeScene),
        ),
      ) as _i5.Scene);

  @override
  bool get activeSceneRequiresPinToExit => (super.noSuchMethod(
        Invocation.getter(#activeSceneRequiresPinToExit),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Scene? sceneByKey(String? key) => (super.noSuchMethod(Invocation.method(
        #sceneByKey,
        [key],
      )) as _i5.Scene?);

  @override
  bool verifyExitPin(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #verifyExitPin,
          [pin],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.Future<_i21.SceneActivationResult> activateScene(
    String? key, {
    String? pin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #activateScene,
          [key],
          {#pin: pin},
        ),
        returnValue: _i10.Future<_i21.SceneActivationResult>.value(
            _i21.SceneActivationResult.activated),
      ) as _i10.Future<_i21.SceneActivationResult>);

  @override
  _i10.Future<_i21.SceneUpdateResult> saveScene(_i5.Scene? scene) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveScene,
          [scene],
        ),
        returnValue: _i10.Future<_i21.SceneUpdateResult>.value(
            _i21.SceneUpdateResult.applied),
      ) as _i10.Future<_i21.SceneUpdateResult>);

  @override
  _i10.Future<_i21.SceneUpdateResult> setSceneWallpaperPath(
    String? key,
    String? wallpaperPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSceneWallpaperPath,
          [
            key,
            wallpaperPath,
          ],
        ),
        returnValue: _i10.Future<_i21.SceneUpdateResult>.value(
            _i21.SceneUpdateResult.applied),
      ) as _i10.Future<_i21.SceneUpdateResult>);

  @override
  _i10.Future<_i21.SceneUpdateResult> setSceneGradientUuid(
    String? key,
    String? gradientUuid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSceneGradientUuid,
          [
            key,
            gradientUuid,
          ],
        ),
        returnValue: _i10.Future<_i21.SceneUpdateResult>.value(
            _i21.SceneUpdateResult.applied),
      ) as _i10.Future<_i21.SceneUpdateResult>);

  @override
  _i10.Future<_i21.SceneUpdateResult> setSceneHideAppBar(
    String? key,
    bool? hideAppBar,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSceneHideAppBar,
          [
            key,
            hideAppBar,
          ],
        ),
        returnValue: _i10.Future<_i21.SceneUpdateResult>.value(
            _i21.SceneUpdateResult.applied),
      ) as _i10.Future<_i21.SceneUpdateResult>);

  @override
  _i10.Future<_i21.SceneUpdateResult> setSceneShowWatchNext(
    String? key,
    bool? showWatchNext,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSceneShowWatchNext,
          [
            key,
            showWatchNext,
          ],
        ),
        returnValue: _i10.Future<_i21.SceneUpdateResult>.value(
            _i21.SceneUpdateResult.applied),
      ) as _i10.Future<_i21.SceneUpdateResult>);

  @override
  _i10.Future<_i21.SceneUpdateResult> setSceneShowAppNames(
    String? key,
    bool? showAppNames,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSceneShowAppNames,
          [
            key,
            showAppNames,
          ],
        ),
        returnValue: _i10.Future<_i21.SceneUpdateResult>.value(
            _i21.SceneUpdateResult.applied),
      ) as _i10.Future<_i21.SceneUpdateResult>);

  @override
  _i10.Future<_i21.SceneUpdateResult> setSceneDisableBackgroundBlur(
    String? key,
    bool? disableBackgroundBlur,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSceneDisableBackgroundBlur,
          [
            key,
            disableBackgroundBlur,
          ],
        ),
        returnValue: _i10.Future<_i21.SceneUpdateResult>.value(
            _i21.SceneUpdateResult.applied),
      ) as _i10.Future<_i21.SceneUpdateResult>);

  @override
  _i10.Future<_i21.SceneUpdateResult> setSceneShowCategoryTitles(
    String? key,
    bool? showCategoryTitles,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSceneShowCategoryTitles,
          [
            key,
            showCategoryTitles,
          ],
        ),
        returnValue: _i10.Future<_i21.SceneUpdateResult>.value(
            _i21.SceneUpdateResult.applied),
      ) as _i10.Future<_i21.SceneUpdateResult>);

  @override
  _i10.Future<_i21.SceneUpdateResult> setSceneAccentColorHex(
    String? key,
    String? accentColorHex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSceneAccentColorHex,
          [
            key,
            accentColorHex,
          ],
        ),
        returnValue: _i10.Future<_i21.SceneUpdateResult>.value(
            _i21.SceneUpdateResult.applied),
      ) as _i10.Future<_i21.SceneUpdateResult>);

  @override
  _i10.Future<_i21.SceneUpdateResult> setScenePin(
    String? key,
    String? pin, {
    String? currentPin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setScenePin,
          [
            key,
            pin,
          ],
          {#currentPin: currentPin},
        ),
        returnValue: _i10.Future<_i21.SceneUpdateResult>.value(
            _i21.SceneUpdateResult.applied),
      ) as _i10.Future<_i21.SceneUpdateResult>);

  @override
  _i10.Future<_i21.SceneUpdateResult> clearScenePin(
    String? key, {
    String? pin,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearScenePin,
          [key],
          {#pin: pin},
        ),
        returnValue: _i10.Future<_i21.SceneUpdateResult>.value(
            _i21.SceneUpdateResult.applied),
      ) as _i10.Future<_i21.SceneUpdateResult>);

  @override
  _i10.Future<_i21.SceneUpdateResult> restoreDefaults({String? pin}) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreDefaults,
          [],
          {#pin: pin},
        ),
        returnValue: _i10.Future<_i21.SceneUpdateResult>.value(
            _i21.SceneUpdateResult.applied),
      ) as _i10.Future<_i21.SceneUpdateResult>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ImagePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePicker extends _i1.Mock implements _i22.ImagePicker {
  MockImagePicker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i6.XFile?> pickImage({
    required _i6.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i6.CameraDevice? preferredCameraDevice = _i6.CameraDevice.rear,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickImage,
          [],
          {
            #source: source,
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #preferredCameraDevice: preferredCameraDevice,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i10.Future<_i6.XFile?>.value(),
      ) as _i10.Future<_i6.XFile?>);

  @override
  _i10.Future<List<_i6.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultiImage,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #limit: limit,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i10.Future<List<_i6.XFile>>.value(<_i6.XFile>[]),
      ) as _i10.Future<List<_i6.XFile>>);

  @override
  _i10.Future<_i6.XFile?> pickMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMedia,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i10.Future<_i6.XFile?>.value(),
      ) as _i10.Future<_i6.XFile?>);

  @override
  _i10.Future<List<_i6.XFile>> pickMultipleMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultipleMedia,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #limit: limit,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i10.Future<List<_i6.XFile>>.value(<_i6.XFile>[]),
      ) as _i10.Future<List<_i6.XFile>>);

  @override
  _i10.Future<_i6.XFile?> pickVideo({
    required _i6.ImageSource? source,
    _i6.CameraDevice? preferredCameraDevice = _i6.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickVideo,
          [],
          {
            #source: source,
            #preferredCameraDevice: preferredCameraDevice,
            #maxDuration: maxDuration,
          },
        ),
        returnValue: _i10.Future<_i6.XFile?>.value(),
      ) as _i10.Future<_i6.XFile?>);

  @override
  _i10.Future<_i6.LostDataResponse> retrieveLostData() => (super.noSuchMethod(
        Invocation.method(
          #retrieveLostData,
          [],
        ),
        returnValue:
            _i10.Future<_i6.LostDataResponse>.value(_FakeLostDataResponse_4(
          this,
          Invocation.method(
            #retrieveLostData,
            [],
          ),
        )),
      ) as _i10.Future<_i6.LostDataResponse>);

  @override
  bool supportsImageSource(_i6.ImageSource? source) => (super.noSuchMethod(
        Invocation.method(
          #supportsImageSource,
          [source],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [FLauncherDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFLauncherDatabase extends _i1.Mock implements _i8.FLauncherDatabase {
  MockFLauncherDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get wasCreated => (super.noSuchMethod(
        Invocation.getter(#wasCreated),
        returnValue: false,
      ) as bool);

  @override
  set wasCreated(bool? _wasCreated) => super.noSuchMethod(
        Invocation.setter(
          #wasCreated,
          _wasCreated,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);

  @override
  _i7.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_5(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i7.MigrationStrategy);

  @override
  _i8.$AppsTable get apps => (super.noSuchMethod(
        Invocation.getter(#apps),
        returnValue: _Fake$AppsTable_6(
          this,
          Invocation.getter(#apps),
        ),
      ) as _i8.$AppsTable);

  @override
  _i8.$CategoriesTable get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: _Fake$CategoriesTable_7(
          this,
          Invocation.getter(#categories),
        ),
      ) as _i8.$CategoriesTable);

  @override
  _i8.$AppsCategoriesTable get appsCategories => (super.noSuchMethod(
        Invocation.getter(#appsCategories),
        returnValue: _Fake$AppsCategoriesTable_8(
          this,
          Invocation.getter(#appsCategories),
        ),
      ) as _i8.$AppsCategoriesTable);

  @override
  _i8.$LauncherSpacersTable get launcherSpacers => (super.noSuchMethod(
        Invocation.getter(#launcherSpacers),
        returnValue: _Fake$LauncherSpacersTable_9(
          this,
          Invocation.getter(#launcherSpacers),
        ),
      ) as _i8.$LauncherSpacersTable);

  @override
  _i8.$FLauncherDatabaseManager get managers => (super.noSuchMethod(
        Invocation.getter(#managers),
        returnValue: _Fake$FLauncherDatabaseManager_10(
          this,
          Invocation.getter(#managers),
        ),
      ) as _i8.$FLauncherDatabaseManager);

  @override
  Iterable<_i7.TableInfo<_i7.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i7.TableInfo<_i7.Table, Object?>>[],
      ) as Iterable<_i7.TableInfo<_i7.Table, Object?>>);

  @override
  List<_i7.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i7.DatabaseSchemaEntity>[],
      ) as List<_i7.DatabaseSchemaEntity>);

  @override
  _i7.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_11(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i7.StreamQueryUpdateRules);

  @override
  _i7.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_12(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i7.GeneratedDatabase);

  @override
  _i7.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_13(
          this,
          Invocation.getter(#options),
        ),
      ) as _i7.DriftDatabaseOptions);

  @override
  _i7.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_14(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i7.DatabaseConnection);

  @override
  _i7.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i20.dummyValue<_i7.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i7.SqlTypes);

  @override
  _i7.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_15(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i7.QueryExecutor);

  @override
  _i9.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_16(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i9.StreamQueryStore);

  @override
  _i7.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_17(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i7.DatabaseConnectionUser);

  @override
  _i10.Future<void> persistApps(Iterable<_i8.AppsCompanion>? applications) =>
      (super.noSuchMethod(
        Invocation.method(
          #persistApps,
          [applications],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateApp(
    String? packageName,
    _i8.AppsCompanion? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateApp,
          [
            packageName,
            value,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteApps(List<String>? packageNames) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteApps,
          [packageNames],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> insertCategory(_i7.Insertable<_i3.Category>? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertCategory,
          [category],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> deleteCategory(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateCategories(List<_i8.CategoriesCompanion>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategories,
          [values],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateCategory(
    int? id,
    _i8.CategoriesCompanion? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [
            id,
            value,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteAppCategory(
    int? categoryId,
    String? packageName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAppCategory,
          [
            categoryId,
            packageName,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> insertAppsCategories(
          List<_i8.AppsCategoriesCompanion>? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAppsCategories,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> replaceAppsCategories(
          List<_i8.AppsCategoriesCompanion>? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceAppsCategories,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> insertSpacer(_i7.Insertable<_i3.LauncherSpacer>? spacer) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSpacer,
          [spacer],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<int> deleteSpacer(int? spacerId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSpacer,
          [spacerId],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<int> updateSpacer(
    int? spacerId,
    _i7.Insertable<_i3.LauncherSpacer>? insertable,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSpacer,
          [
            spacerId,
            insertable,
          ],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<void> updateSpacers(
          Iterable<_i8.LauncherSpacersCompanion>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSpacers,
          [values],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i3.Category>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i10.Future<List<_i3.Category>>.value(<_i3.Category>[]),
      ) as _i10.Future<List<_i3.Category>>);

  @override
  _i10.Future<List<_i3.LauncherSpacer>> getLauncherSpacers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLauncherSpacers,
          [],
        ),
        returnValue:
            _i10.Future<List<_i3.LauncherSpacer>>.value(<_i3.LauncherSpacer>[]),
      ) as _i10.Future<List<_i3.LauncherSpacer>>);

  @override
  _i10.Future<List<_i8.AppCategory>> getAppsCategories() => (super.noSuchMethod(
        Invocation.method(
          #getAppsCategories,
          [],
        ),
        returnValue:
            _i10.Future<List<_i8.AppCategory>>.value(<_i8.AppCategory>[]),
      ) as _i10.Future<List<_i8.AppCategory>>);

  @override
  _i10.Future<List<_i18.App>> getApplications() => (super.noSuchMethod(
        Invocation.method(
          #getApplications,
          [],
        ),
        returnValue: _i10.Future<List<_i18.App>>.value(<_i18.App>[]),
      ) as _i10.Future<List<_i18.App>>);

  @override
  _i10.Future<int?> nextAppCategoryOrder(int? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #nextAppCategoryOrder,
          [categoryId],
        ),
        returnValue: _i10.Future<int?>.value(),
      ) as _i10.Future<int?>);

  @override
  _i7.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_18(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i7.Migrator);

  @override
  _i10.Future<void> beforeOpen(
    _i7.QueryExecutor? executor,
    _i7.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Stream<List<Map<String, Object?>>> createStream(
          _i9.QueryStreamFetcher? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i10.Stream<List<Map<String, Object?>>>.empty(),
      ) as _i10.Stream<List<Map<String, Object?>>>);

  @override
  T alias<T, D>(
    _i7.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i20.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i7.TableInfo<_i7.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i7.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Stream<Set<_i7.TableUpdate>> tableUpdates(
          [_i7.TableUpdateQuery? query = const _i7.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i10.Stream<Set<_i7.TableUpdate>>.empty(),
      ) as _i10.Stream<Set<_i7.TableUpdate>>);

  @override
  _i10.Future<T> doWhenOpened<T>(
          _i10.FutureOr<T> Function(_i7.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i20.ifNotNull(
              _i20.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i10.Future<T>.value(v),
            ) ??
            _FakeFuture_19<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i10.Future<T>);

  @override
  _i7.InsertStatement<T, D> into<T extends _i7.Table, D>(
          _i7.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_20<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i7.InsertStatement<T, D>);

  @override
  _i7.UpdateStatement<Tbl, R> update<Tbl extends _i7.Table, R>(
          _i7.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_21<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i7.UpdateStatement<Tbl, R>);

  @override
  _i7.SimpleSelectStatement<T, R> select<T extends _i7.HasResultSet, R>(
    _i7.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_22<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i7.SimpleSelectStatement<T, R>);

  @override
  _i7.JoinedSelectStatement<T, R> selectOnly<T extends _i7.HasResultSet, R>(
    _i7.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_23<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i7.JoinedSelectStatement<T, R>);

  @override
  _i7.Selectable<_i7.TypedResult> selectExpressions(
          Iterable<_i7.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeSelectable_24<_i7.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i7.Selectable<_i7.TypedResult>);

  @override
  _i7.DeleteStatement<T, D> delete<T extends _i7.Table, D>(
          _i7.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_25<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i7.DeleteStatement<T, D>);

  @override
  _i10.Future<int> customUpdate(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.TableInfo<_i7.Table, dynamic>>? updates,
    _i7.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<int> customInsert(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.TableInfo<_i7.Table, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<List<_i7.QueryRow>> customWriteReturning(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.TableInfo<_i7.Table, dynamic>>? updates,
    _i7.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i10.Future<List<_i7.QueryRow>>.value(<_i7.QueryRow>[]),
      ) as _i10.Future<List<_i7.QueryRow>>);

  @override
  _i7.Selectable<_i7.QueryRow> customSelect(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_24<_i7.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i7.Selectable<_i7.QueryRow>);

  @override
  _i7.Selectable<_i7.QueryRow> customSelectQuery(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_24<_i7.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i7.Selectable<_i7.QueryRow>);

  @override
  _i10.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<T> transaction<T>(
    _i10.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i20.ifNotNull(
              _i20.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i10.Future<T>.value(v),
            ) ??
            _FakeFuture_19<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i10.Future<T>);

  @override
  _i10.Future<T> exclusively<T>(_i10.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i20.ifNotNull(
              _i20.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i10.Future<T>.value(v),
            ) ??
            _FakeFuture_19<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i10.Future<T>);

  @override
  _i10.Future<void> batch(
          _i10.FutureOr<void> Function(_i7.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i7.GenerationContext $write(
    _i7.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_26(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i7.GenerationContext);

  @override
  _i7.GenerationContext $writeInsertable(
    _i7.TableInfo<_i7.Table, dynamic>? table,
    _i7.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_26(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i7.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i20.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);
}

/// A class which mocks [ImageProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageProvider<T extends Object> extends _i1.Mock
    implements _i11.ImageProvider<T> {
  MockImageProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.ImageStream resolve(_i11.ImageConfiguration? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolve,
          [configuration],
        ),
        returnValue: _FakeImageStream_27(
          this,
          Invocation.method(
            #resolve,
            [configuration],
          ),
        ),
      ) as _i11.ImageStream);

  @override
  _i11.ImageStream createStream(_i11.ImageConfiguration? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [configuration],
        ),
        returnValue: _FakeImageStream_27(
          this,
          Invocation.method(
            #createStream,
            [configuration],
          ),
        ),
      ) as _i11.ImageStream);

  @override
  _i10.Future<_i11.ImageCacheStatus?> obtainCacheStatus({
    required _i11.ImageConfiguration? configuration,
    _i11.ImageErrorListener? handleError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #obtainCacheStatus,
          [],
          {
            #configuration: configuration,
            #handleError: handleError,
          },
        ),
        returnValue: _i10.Future<_i11.ImageCacheStatus?>.value(),
      ) as _i10.Future<_i11.ImageCacheStatus?>);

  @override
  void resolveStreamForKey(
    _i11.ImageConfiguration? configuration,
    _i11.ImageStream? stream,
    T? key,
    _i11.ImageErrorListener? handleError,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #resolveStreamForKey,
          [
            configuration,
            stream,
            key,
            handleError,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<bool> evict({
    _i11.ImageCache? cache,
    _i11.ImageConfiguration? configuration = _i11.ImageConfiguration.empty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #evict,
          [],
          {
            #cache: cache,
            #configuration: configuration,
          },
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);

  @override
  _i10.Future<T> obtainKey(_i11.ImageConfiguration? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #obtainKey,
          [configuration],
        ),
        returnValue: _i20.ifNotNull(
              _i20.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #obtainKey,
                  [configuration],
                ),
              ),
              (T v) => _i10.Future<T>.value(v),
            ) ??
            _FakeFuture_19<T>(
              this,
              Invocation.method(
                #obtainKey,
                [configuration],
              ),
            ),
      ) as _i10.Future<T>);

  @override
  _i11.ImageStreamCompleter loadBuffer(
    T? key,
    _i11.DecoderBufferCallback? decode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadBuffer,
          [
            key,
            decode,
          ],
        ),
        returnValue: _FakeImageStreamCompleter_28(
          this,
          Invocation.method(
            #loadBuffer,
            [
              key,
              decode,
            ],
          ),
        ),
      ) as _i11.ImageStreamCompleter);

  @override
  _i11.ImageStreamCompleter loadImage(
    T? key,
    _i11.ImageDecoderCallback? decode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadImage,
          [
            key,
            decode,
          ],
        ),
        returnValue: _FakeImageStreamCompleter_28(
          this,
          Invocation.method(
            #loadImage,
            [
              key,
              decode,
            ],
          ),
        ),
      ) as _i11.ImageStreamCompleter);
}
